### ISSUE TITLE
about the generated synth_img in encode_image.py

### ISSUE THREAD

**Issue by BERYLSHEEP** [pacifinapacific/StyleGAN_LatentEditor#2]
https://github.com/pacifinapacific/StyleGAN_LatentEditor/blob/3695fb4d78b1ef33bba5b4b249da630b97a937df/encode_image.py#L64

I am confused about the operation on the synth_img. Why not just pass the synth_img to calculate the loss?  Can anyone tell me ?

**Comment by pacifinapacific** [comment]
https://github.com/pacifinapacific/StyleGAN_LatentEditor/blob/3695fb4d78b1ef33bba5b4b249da630b97a937df/encode_image.py#L65

I used synth_img to calculate loss.Can you tell me specifically where you are confused?

**Comment by BERYLSHEEP** [comment]
Thanks! My problem is solved.
