### ISSUE TITLE
boundary directory is missing

### ISSUE THREAD

**Issue by BERYLSHEEP** [pacifinapacific/StyleGAN_LatentEditor#3]
https://github.com/pacifinapacific/StyleGAN_LatentEditor/blob/3695fb4d78b1ef33bba5b4b249da630b97a937df/semantic_edit.py#L58

hello! I found the directory and corresponding boundary files is missing in this Github.  Will you provided for us?

**Comment by pacifinapacific** [comment]
This repository does not support boundary learning, so I cannot provide it.
But you can get the boundaries folder from the thesis author's repository
https://github.com/ShenYujun/InterFaceGAN

**Comment by BERYLSHEEP** [comment]
Thanks a lot!
