### ISSUE TITLE
weight_convert.py error  assert state["version"] in [2, 3] AssertionError

### ISSUE THREAD

**Issue by ahmedshingaly** [pacifinapacific/StyleGAN_LatentEditor#9]
I am trying to convert my trainned model from tensorflow to pytorch version using weight_convert.py however it shows below error 

`Traceback (most recent call last):
  File "weight_convert.py", line 37, in <module>
    weights =pickle.load(open(tensorflow_dir+weight_name+".pkl",'rb'))
  File "/home/ahmed/Documents/3DAI/StyleGAN_LatentEditor/dnnlib/tflib/network.py", line 279, in __setstate__
    assert state["version"] in [2, 3]
AssertionError
`
thank you in advance for reply

**Comment by pacifinapacific** [comment]
Is your weight file an official pretrained model of StyleGAN(https://github.com/NVlabs/stylegan)?

**Comment by ahmedshingaly** [comment]
yes 
stylegan2 
1024*1024

**Comment by pacifinapacific** [comment]
This repository supports only StyleGAN; StyleGAN2 is not supported.

**Comment by ahmedshingaly** [comment]
I see, 
so your saying I need to train my image using stylegan (1024*1024) resolution then 
weight_convert.py will be able to convert .pkl to .pt

thanks
